name: Money
version: '4.12'
main: de.fabian.server2026.money.Money
api-version: '1.21'
authors: [ DoktorNilson ]

commands:
  money:
    description: Zeigt dein Kontostand an
    usage: /<command> [settings|top]
  givebank:
    description: Gibt einen Bankblock
    usage: /<command>
    permission: money.givebank
  moneysettings:
    description: Oeffnet Einstellungen
  pay:
    description: Ueberweise Geld an einen Spieler
  shop:
    description: Oeffnet den Shop
    usage: /<command> [reload|price <item>]
  shoplog:
    description: Zeigt Shop-Kauf-Logs an
    usage: /<command> [anzahl|player <name>|item <item>|reload]
    permission: money.shoplog
  bank:
    description: Bank-Commands
    usage: /<command> list
  achievements:
    description: Zeigt deine Achievements
    usage: /<command>
