name: Money
version: '4.11'
main: de.fabian.server2026.money.Money
api-version: '1.21'
authors: [ DoktorNilson ]

commands:
  money:
    description: Zeigt dein Kontostand an
    usage: /<command>
  givebank:
    description: Gibt einen Bankblock
    usage: /<command>
    permission: money.givebank
  moneysettings:
    description: Oeffnet Einstellungen
  pay:
    description: Ueberweise Geld an einen Spieler
  shop:
    description: Oeffnet den Shop
  shoplog:
    description: Zeigt Shop-Kauf-Logs an
    usage: /<command> [anzahl|player <name>|item <item>|reload]
    permission: money.shoplog
