name: Money
version: '4.02'
main: de.fabian.server2026.money.Money
api-version: '1.21'
authors: [ DoktorNilson ]

commands:
  money:
    description: Zeigt dein Kontostand an
    usage: /<command>
  givebank:
    description: Gibt einen Bankblock
    usage: /<command>
    permission: money.givebank
  moneysettings:
    description: Öffnet Einstellungen
  pay:
    description: Überweise Geld an einen Spieler
  shop:
    description: Öffnet den Shop
